apiVersion: v1
kind: Secret
metadata:
  name: cloud-final-secrets
type: Opaque
stringData:
  JWT_SECRET: replace-this-in-github-environments-or-render
  SMTP_API_KEY: replace-this-in-github-environments-or-render
